### PR TITLE
creating the file readingtime.html.twig

### PR DESCRIPTION
**Pull request by B1gG**
this will be used to include the reading time on a blog post

### CODE REVIEW

**Comment by paulhibbitts** [comment]
Thanks for the PR @B1gG  - however, it looks like the Breadcrumb plugin is being checked for and not the ReadingTime plugin?

**Comment by B1gG** [comment]
Yes, you are absolutely right, anbd there is where I will need your help, I am not a PHP guy :)
In the fork I have I included the scripts and the check, probably you can check it to see if that could work.

**Comment by paulhibbitts** [comment]
No problem, I appreciate your contributions! You would only need Twig for the check, it will look like this:

```
{% if config.plugins.readingtime.enabled %}
```
I can make this change on my end.

Re: dependency, I am currently trying to further minimize them so let's not add that for now. With your script changes if a user installs ReadingTime they will be able to use it right away and not do any script changes.

I will accept the changes now, do a bit of fine-tuning, and give you a status update.

Cheers,
Paul

**Comment by paulhibbitts** [comment]
Hi @B1gG , I've added ReadingTime to the blog list items as well as your other changes and have a working prototype going at https://blog.hibbittsdesign.org/

Please let me know what you think and then I can release the theme with this new feature (and will credit you in the ChangeLog🙂).

**Comment by paulhibbitts** [comment]
Theme update now released with this feature, thanks again for the PRs!

**Comment by B1gG** [comment]
great stuff !!!, thanks.
I am also working to update the breadcrumbs plugin to add support for schema as per google advisory

**Pull request merged**
